services:
  immich-reversegeo:
    build:
      context: .
      dockerfile: src/ImmichReverseGeo.Web/Dockerfile
    image: immich-reversegeo:local
    ports:
      - "8080:8080"
    volumes:
      - ./reversegeo/config:/config
      - ./reversegeo/data:/data
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
